[phases.setup]
nixPkgs = ['python3', 'blas', 'lapack', 'atlas']

[phases.install]
aptPkgs = ['gcc', 'gfortran', 'python3-dev', 'python3-pip']
cmds = [
    'python -m pip install --upgrade pip',
    'pip install numpy',
    'pip install scipy==1.12.0',
    'pip install -r requirements.txt'
] 