[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
aptPkgs = ['gcc', 'gfortran', 'python3-dev', 'libblas-dev', 'liblapack-dev']
cmds = [
    'python -m venv /opt/venv',
    'source /opt/venv/bin/activate',
    'pip install -r requirements.txt'
] 