[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
aptPkgs = ['gcc', 'gfortran', 'python3-dev', 'libblas-dev', 'liblapack-dev']
cmds = [
    'pip install -r requirements.txt'
] 